INSERT INTO ASSISTANCE (NAME, DESCRIPTION) VALUES ('Plumbing', 'Description 1');
INSERT INTO ASSISTANCE (NAME, DESCRIPTION) VALUES ('Power Supply', 'Description 2');
INSERT INTO ASSISTANCE (NAME, DESCRIPTION) VALUES ('Masonry', 'Description 3');
INSERT INTO ASSISTANCE (NAME, DESCRIPTION) VALUES ('Carpentry', 'Description 4');